spring.application.name=SustainableFoodTracker
spring.datasource.url=jdbc:postgresql://localhost:5432/sustainable-foodtracker
spring.datasource.username=postgres
spring.datasource.password=9042
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql= true
server.port=8081